FROM python:3.12-slim

RUN apt-get update && apt-get install -y libjpeg-dev zlib1g-dev libpng-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/app

CMD ["python", "tile_service_app/worker.py"]