import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv('DATABASE_URL')
SOURCE_IMAGES_PATH = os.getenv('SOURCE_IMAGES_PATH')
REDIS_URL = os.getenv('REDIS_URL')
TILES_BASE_PATH = os.getenv('TILES_BASE_PATH')
TILE_SERVICE_TASK = os.getenv('TILE_SERVICE_TASK')
MAX_TAGS_PER_MAP = 10
MAX_TAG_LEN = 25
SHARE_ID_TRIES = 10
DESCRIPTION_MAX_LENGTH = 50000