"""create initial map service tables

Revision ID: e7b5503c9775
Revises: 
Create Date: 2026-05-06 18:00:31.858289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7b5503c9775'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maps',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('share_id', sa.String(), nullable=True),
    sa.Column('owner_username', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tiles_version', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('max_zoom', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maps_id'), 'maps', ['id'], unique=True)
    op.create_index(op.f('ix_maps_owner_id'), 'maps', ['owner_id'], unique=False)
    op.create_index(op.f('ix_maps_share_id'), 'maps', ['share_id'], unique=True)
    op.create_index(op.f('ix_maps_status'), 'maps', ['status'], unique=False)
    op.create_index(op.f('ix_maps_visibility'), 'maps', ['visibility'], unique=False)
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("""
               CREATE INDEX IF NOT EXISTS ix_maps_title_trgm
                   ON maps
                   USING GIN (title gin_trgm_ops)
               """)
    op.create_table('tags',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=True)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_tags_name_trgm
            ON tags
            USING GIN (name gin_trgm_ops)
        """
    )
    op.create_table('locations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('map_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=True)
    op.create_index(op.f('ix_locations_map_id'), 'locations', ['map_id'], unique=False)
    op.create_table('map_tags',
    sa.Column('map_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tag_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_id', 'tag_id'),
    sa.UniqueConstraint('map_id', 'tag_id', name='uq_map_tags_map_id_tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_tags')
    op.drop_index(op.f('ix_locations_map_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.execute("DROP INDEX IF EXISTS ix_tags_name_trgm")
    op.drop_table('tags')
    op.drop_index(op.f('ix_maps_visibility'), table_name='maps')
    op.drop_index(op.f('ix_maps_status'), table_name='maps')
    op.drop_index(op.f('ix_maps_share_id'), table_name='maps')
    op.drop_index(op.f('ix_maps_owner_id'), table_name='maps')
    op.drop_index(op.f('ix_maps_id'), table_name='maps')
    op.execute("DROP INDEX IF EXISTS ix_maps_title_trgm")
    op.drop_table('maps')
    # ### end Alembic commands ###
