import os
import dotenv

dotenv.load_dotenv()

USER_SERVICE_URL = os.getenv("USER_SERVICE_URL")
MAP_SERVICE_URL = os.getenv("MAP_SERVICE_URL")
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
FRONTEND_URL = os.getenv("FRONTEND_URL")

MAP_UPLOAD_TIMEOUT_SECONDS = 180.0
DEFAULT_PROXY_TIMEOUT_SECONDS = 10.0

INITIAL_SNAPSHOT_GRACE_SECONDS = 15
PROGRESS_STALE_TIMEOUT_SECONDS = 12
PUBSUB_POLL_TIMEOUT_SECONDS = 5.0
LOOP_SLEEP_SECONDS = 0.05