gantt
    title Проект "Fantasy Maps" - История разработки
    dateFormat  YYYY-MM-DD
    section Проектирование
    Проектирование ER диаграмм и C4 модели :done, 2025-05-15, 1d
    section Бэкенд
    Разработка user-service, map-service, api-gateway :done, 2025-05-16, 3d
    docker-compose, юнит-тесты, интеграционные тесты :done, 2025-05-19, 2d
    Подключение NGINX :done, 2025-05-21, 1d
    section Изучение технологий фронта
    Изучение основ JS и React :done, 2025-05-22, 4d
    section Фронтенд разработка
    Разработка архитектуры сайта, написание основных страниц :done, 2025-05-26, 2d
    Рефакторинг фронтенда :done, 2025-05-28, 1d
    Изучение CSS, Tailwind, shadcn :done, 2025-05-29, 1d
    Приведение сайта к красивому стилизованному виду :done, 2025-05-30, 3d
    section TileService и интеграция
    Разработка tile_service. Изучение Redis + RQ :done, 2025-06-02, 2d
    Подключение tile_service к остальным сервисам и фронтенду :done, 2025-06-04, 2d
    section Финальная полировка
    Полировка сайта :done, 2025-06-06, 2d